osx_image: xcode8.3

# Needed for node_canvas build
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
  - CXX=g++-4.8

dist: trusty
sudo: false

language: node_js
node_js: "6"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds


script:
  - npm update music-api
  - node build

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*.deb
    - releases/*.dmg
    - releases/*.exe
  skip_cleanup: true

branches:
  only:
  - master
  - ci-test
  
notifications:
  email: false